version: '3.5' # We use version 3.5 syntax
services: # Here we define our service(s)
    itinarys-app: # The name of the service
      container_name: itinarysfront  # Container name
      build: ./ # Location of our Dockerfile
      volumes: # Volume binding
        - './:/usr/src/app' 
      ports: 
        - '4200:4200' # Port mapping
      command: > 
        bash -c "ng serve --prod --host 0.0.0.0 --port 4200"